Infinit scroll
ChizhovMN/POKEMON-API pull request #2
Opened 2023-02-17 12:26 UTC by ChizhovMN

2023-02-20 10:28 UTC, nikolai-chizhov-softteco requested changes
Remove components folder from 'pages'

2023-02-20 11:15 UTC, nikolai-chizhov-softteco requested changes

2023-02-21 11:12 UTC, ChizhovMN commented on src/pages/components/infinitScrollPage.tsx
> +          data: {
Not in all files can do this changes

2023-02-21 13:47 UTC, nikolai-chizhov-softteco approved these changes

2023-02-21 15:33 UTC, merged